---
abstract: 'Deploy to Heroku'
author:
  - 'Glen Hinkle'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300017, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojolicious-Command-deploy-heroku
requires:
  File::Path: 2.08
  File::Slurp: 9999.19
  IPC::Cmd: 0.78
  Mojolicious: 2.48
  Mojolicious::Command::deploy: 0.01
  Net::Heroku: 0.08
resources:
  repository: git://github.com/tempire/mojolicious-command-deploy-heroku.git
version: 0.08
